### ISSUE TITLE
Execute an Update Operation should be Long instead of Integer

### ISSUE THREAD

**Issue by fsalem** [ufoss-org/kotysa#131]
The latest R2DBC dependancies expect update operation to return Long. The current implementation of Kotysa return Integer instead.

java.lang.Exception: Error in acquiring lock: java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Integer (java.lang.Long and java.lang.Integer are in module java.base of loader 'bootstrap')
        at org.ufoss.kotysa.r2dbc.SqlClientUpdateR2dbc$Return.execute$suspendImpl(SqlClientUpdateR2dbc.kt:87)
        at org.ufoss.kotysa.r2dbc.SqlClientUpdateR2dbc$Return$execute$1.invokeSuspend(SqlClientUpdateR2dbc.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)

**Comment by pull-vert** [comment]
Hello @fsalem , I am actively working on Kotysa release 3.0.0, it should be ready in the next few weeks !

This upcoming Kotysa release will contain a bump to R2DBC 1.0 and Spring 6.0 (among other updates), see issue #113 that already tracks this issue.

**Comment by pull-vert** [comment]
Hi @fsalem 
Kotysa 3.0.0 is released, it is compatible with R2DBC 1.0.0 !
